#ifndef CPAIRS_H
#define CPAIRS_H

#define CP_GREEN COLOR_PAIR(1)
#define CP_CYAN COLOR_PAIR(2)
#define CP_BLUE COLOR_PAIR(3)
#define CP_YELLOW COLOR_PAIR(4)
#define CP_PURPLE COLOR_PAIR(5)
#define CP_RED COLOR_PAIR(6)

#endif
