#include "entity_types.h"

//The data in this file is based on Liberal Crime Squad's art/creatures.xml file.

//Turns out, you don't have to define all the elements of an array, the rest is filled with zeroes.
//This makes creating such definitions much easier.

#define A_DOGYEARS {2,6}
#define A_CHILD {7,10}
#define A_TEENAGER {14,17}
#define A_YOUNGADULT {18,35}
#define A_MATURE {20,59}
#define A_GRADUATE {26,59}
#define A_MIDDLEAGED {35,59}
#define A_SENIOR {65,94}

const char* type_description (struct t_creature* e) {

	switch(e->type) {
		case ET_BOUNCER: return "Club Security";
		case ET_SECURITYGUARD: return "Security Guard";
		case ET_SCIENTIST_LABTECH: return "Lab Tech";
		case ET_SCIENTIST_EMINENT: return "Eminent Scientist";
		case ET_POLITICIAN: return "Politician";
		case ET_CORPORATE_MANAGER: return "Corporate Manager";
		case ET_CORPORATE_CEO: return "Corporate CEO";
		case ET_WORKER_SERVANT: return "Servant";
		case ET_WORKER_JANITOR: return "Janitor";
		case ET_WORKER_SWEATSHOP: return "Sweatshop Worker";
		case ET_WORKER_FACTORY_NONUNION:
		if (e->align >= ALIGN_LIBERAL) return "New Union Worker"; else return "Nonunion Worker";
		case ET_WORKER_FACTORY_CHILD: return "Child Worker";
		case ET_WORKER_SECRETARY: return "Secretary";
		case ET_WORKER_FACTORY_UNION:
		if (e->align <= ALIGN_CONSERVATIVE) return "Ex-Union Worker"; else return "Factory Worker";
		case ET_LANDLORD: return "Landlord";
		case ET_TEENAGER: return "Teenager";
		case ET_COP: return "Police Officer";
		case ET_SWAT: return "SWAT Officer";
		case ET_DEATHSQUAD: return "Death Squad Officer";
		case ET_FIREFIGHTER: return "Firefighter";
		case ET_EDUCATOR: return "Educator";
		case ET_GANGUNIT: return "Police Gang Unit";
		case ET_JUDGE_LIBERAL:
		if (e->align <= ALIGN_CONSERVATIVE) return "Jaded Liberal Judge"; else return "Liberal Judge";
		case ET_JUDGE_CONSERVATIVE:
		if (e->align >= ALIGN_LIBERAL) return "Enlightened Judge"; else return "Hangin' Judge";
		case ET_AGENT: return "Agent";
		case ET_SECRET_SERVICE: return "Secret Service";
		case ET_RADIOPERSONALITY: return "Radio Personality";
		case ET_NEWSANCHOR: return "News Anchor";
		case ET_GENETIC: return "Genetic Monster";
		case ET_GUARDDOG: return "Guard Dog";
		case ET_PRISONER: return "Prisoner";
		case ET_JUROR: return "Juror";
		case ET_LAWYER: return "Lawyer";
		case ET_SEWERWORKER: return "Sewer Worker";
		case ET_COLLEGESTUDENT: return "College Student";
		case ET_MUSICIAN: return "Musician";
		case ET_MATHEMATICIAN: return "Mathematician";
		case ET_TEACHER: return "Teacher";
		case ET_HSDROPOUT: return "High School Dropout";
		case ET_BUM: return "Transient";
		case ET_GANGMEMBER: return "Gang Member";
		case ET_CRACKHEAD: return "Crackhead";
		case ET_PRIEST: return "Priest";
		case ET_ENGINEER: return "Engineer";
		case ET_FASTFOODWORKER: return "Fast Food Worker";
		case ET_BAKER: return "Baker";
		case ET_BARISTA: return "Barista";
		case ET_BARTENDER: return "Bartender";
		case ET_TELEMARKETER: return "Telemarketer";
		case ET_CARSALESMAN: return "Car Salesperson";
		case ET_OFFICEWORKER: return "Office Worker";
		case ET_FOOTBALLCOACH: return "Football Coach";
		case ET_PROSTITUTE: return "Prostitute";
		case ET_MAILMAN: return "Mail Carrier";
		case ET_GARBAGEMAN: return "Garbage Collector";
		case ET_PLUMBER: return "Plumber";
		case ET_CHEF: return "Chef";
		case ET_CONSTRUCTIONWORKER: return "Construction Worker";
		case ET_AMATEURMAGICIAN: return "Amateur Magician";
		case ET_TANK: return "M1 Abrams Tank";
		case ET_MERC: return "Elite Security";
		case ET_HICK: return "Redneck";
		case ET_SOLDIER: return "Soldier";
		case ET_VETERAN: return "Veteran";
		case ET_HARDENED_VETERAN: return "Hardened Veteran";
		case ET_PRISONGUARD: return "Prison Guard";
		case ET_HIPPIE: return "Hippie";
		case ET_CRITIC_ART: return "Art Critic";
		case ET_CRITIC_MUSIC: return "Music Critic";
		case ET_SOCIALITE: return "Socialite";
		case ET_PROGRAMMER: return "Programmer";
		case ET_RETIREE: return "Retiree";
		case ET_PAINTER: return "Painter";
		case ET_SCULPTOR: return "Sculptor";
		case ET_AUTHOR: return "Author";
		case ET_JOURNALIST: return "Journalist";
		case ET_DANCER: return "Dancer";
		case ET_PHOTOGRAPHER: return "Photographer";
		case ET_CAMERAMAN: return "Camera Operator"; //for all the gender-neutral terms used in LCS, I'm surprised "Cameraman" wasn't replaced.
		case ET_HAIRSTYLIST: return "Hairstylist";
		case ET_FASHIONDESIGNER: return "Fashion Designer";
		case ET_CLERK: return "Clerk";
		case ET_THIEF: return "Professional Thief";
		case ET_ACTOR: return "Actor";
		case ET_YOGAINSTRUCTOR: return "Yoga Instructor";
		case ET_MARTIALARTIST: return "Martial Artist";
		case ET_ATHLETE: return "Athlete";
		case ET_BIKER: return "Biker";
		case ET_TRUCKER: return "Truck Driver";
		case ET_TAXIDRIVER: return "Taxi Driver";
		case ET_NUN: return "Nun";
		case ET_MUTANT: return "Mutant";
		case ET_DOCTOR: return "Doctor";
		case ET_NURSE: return "Nurse";
		case ET_CCS_VIGILANTE: return "Vigilante";
		case ET_CCS_ARCHCONSERVATIVE: return "CCS Officer";
		case ET_POLITICALACTIVIST: return "Political Activist";
		case ET_CCS_MOLOTOV: return "Arsonist";
		case ET_CCS_SNIPER: return "Sniper";
		case ET_PSYCHOLOGIST: return "Psychologist";
		case ET_LOCKSMITH: return "Locksmith";
		case ET_MILITARYPOLICE: return "Military Police";
		case ET_SEAL: return "Navy SEAL";
		case ET_MILITARYOFFICER: return "Military Officer";
		case ET_BANK_TELLER: return "Bank Teller";
		case ET_BANK_MANAGER: return "Bank Manager";

	}

	return NULL;
}

struct t_creature_generate_rules type_rules[ENTT_COUNT] = {
	{.type = ET_BOUNCER, .gender = EG_MBIAS,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{3,10},{3,10},{4,10}},
		.skill = {ES_HANDTOHAND},
		.skilllim = {{1,3}}
	},
	{.type = ET_SECURITYGUARD, .gender= EG_MBIAS,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{3,10},{3,10},{2,10}},
		.infiltration = {0,20},
		.skill = {ES_PISTOL},
		.skilllim = {{1,3}},
	},
	{.type = ET_SCIENTIST_LABTECH, .gender = EG_MBIAS,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_INT},
		.attrlim = {{5,10}},
		.infiltration = {0,30},
		.skill = {ES_COMPUTERS,ES_SCIENCE},
		.skilllim = {{1,2},{3,6}},
	},
	{.type = ET_SCIENTIST_EMINENT, .gender = EG_MBIAS,
		.age = A_MIDDLEAGED,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_INT, EA_WIS},
		.attrlim = {{10,10},{6,10}},
		.infiltration = {50,80},
		.juice = {100,150},
		.money = {20,60},
		.skill = {ES_SCIENCE,ES_WRITING},
		.skilllim = {{6,11},{1,3}},
	},
	{.type = ET_CORPORATE_MANAGER, .gender = EG_MBIAS,
		.age = A_MATURE, .align = ALIGN_CONSERVATIVE,
		.attrs = {EA_CHA, EA_INT, EA_WIS},
		.attrlim = {{5,10},{4,10},{5,10}},
		.infiltration = {0,50},
		.money = {40,80},
		.skill = {ES_BUSINESS},
		.skilllim = {{3,6}},
	},
	{.type = ET_CORPORATE_CEO, .gender = EG_MBIAS,
		.age = A_MIDDLEAGED, .align = ALIGN_CONSERVATIVE,
		.attrs = {EA_CHA,EA_INT,EA_WIS},
		.attrlim = {{7,10},{7,10},{12,12}},
		.infiltration = {100,100},
		.juice = {1000,1000},
		.money = {1000,2000},
		.skill = {ES_BUSINESS,ES_DODGE,ES_PISTOL},
		.skilllim = {{10,15},{10,15},{10,15}},
	},
	{.type = ET_WORKER_SERVANT,
		.age = A_MATURE, .align = ALIGN_LIBERAL, .money = {0,1}
	},
	{.type = ET_WORKER_JANITOR,
		.age = A_MATURE},
	{.type = ET_WORKER_SWEATSHOP,
		.age = A_MATURE, .align = ALIGN_LIBERAL,
		.juice = {-20,-20},
		.skill = {ES_TAILORING},
		.skilllim = {{1,5}},
	},
	{.type = ET_WORKER_FACTORY_NONUNION,
		.age = A_MATURE, .gender = EG_MBIAS,
		.attrs = {EA_STR}, .attrlim = {{5,10}},
	},
	{.type = ET_WORKER_FACTORY_CHILD,
		.age = A_CHILD, .align = ALIGN_LIBERAL,
		.attrs = {EA_HRT},
		.attrlim = {{8,10}},
		.money = {0,1},
	},
	{.type = ET_WORKER_SECRETARY,
		.age = A_MATURE,
		.attrs = {EA_INT},
		.attrlim = {{2,10}},
		.skill = {ES_WRITING},
		.skilllim = {{1,2}},
	},
	{.type = ET_WORKER_FACTORY_UNION,
		.age = A_MATURE,
		.align = ALIGN_LIBERAL,
		.gender = EG_MBIAS,
		.attrs = {EA_STR},
		.attrlim = {{5,10}},
	},
	{.type = ET_LANDLORD,
		.age = A_MATURE,
		.align = ALIGN_MODERATE,
		.attrs = {EA_INT,EA_WIS},
		.attrlim = {{4,10},{4,10}},
		.gender = EG_MBIAS,
		.money = {120,240},
		.skill = {ES_BUSINESS},
		.skilllim = {{3,6}},
	},
	{.type = ET_TEENAGER,
		.age = A_TEENAGER,
	},
	{.type = ET_COP,
		.age = A_MATURE,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{3,10},{3,10},{3,10}},
		.gender = EG_MBIAS,
		.infiltration = {30,60},
		.juice = {10,60},
		.skill = {ES_DRIVING,ES_PSYCHOLOGY},
		.skilllim = {{1,2},{2,3}},
	},
	{.type = ET_SWAT,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_STR,EA_WIS},
		.attrlim = {{3,10},{3,10},{3,10},{4,10}},
		.gender = EG_MBIAS,
		.infiltration = {30,60},
		.juice = {40,90},
		.skill = {ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE,ES_SHOTGUN},
		.skilllim = {{1,2},{1,2},{1,4},{1,4},{1,4},{1,4}},
	},
	{.type = ET_DEATHSQUAD,
		.age = A_YOUNGADULT,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_STR,EA_WIS},
		.attrlim = {{3,10},{3,10},{3,10},{6,10}},
		.gender = EG_MBIAS,
		.infiltration = {50,80},
		.juice = {90,140},
		.skill = {ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE,ES_SHOTGUN},
		.skilllim = {{1,2},{1,2},{1,2},{2,5},{2,5},{1,2}},
	},
	{.type = ET_FIREFIGHTER,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{3,10},{3,10},{3,10}},
		.infiltration = {0,30},
	},
	{.type = ET_EDUCATOR,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_STR,EA_WIS},
		.attrlim = {{3,10},{3,10},{3,10},{4,10}},
		.infiltration = {0,30},
		.skill = {ES_CLUB,ES_DRIVING,ES_HANDTOHAND,ES_PSYCHOLOGY,ES_RIFLE,ES_SHOTGUN},
		.skilllim = {{1,2},{0,1},{1,2},{3,6},{1,3},{1,3}},
	},
	{.type = ET_GANGUNIT,
		.age = A_YOUNGADULT,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_STR,EA_WIS},
		.attrlim = {{3,10},{3,10},{3,10},{5,10}},
		.infiltration = {30,60},
		.juice = {40,90},
		.gender = EG_MBIAS,
		.skill = {ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE,ES_SHOTGUN},
		.skilllim = {{1,2},{1,2},{1,4},{2,5},{1,3},{1,3}},
	},
	{.type = ET_JUDGE_LIBERAL,
		.age = A_MIDDLEAGED,
		.align = ALIGN_LIBERAL,
		.attrs = {EA_HRT,EA_INT},
		.attrlim = {{10,10},{5,10}},
		.money = {20,60},
		.skill = {ES_LAW,ES_WRITING},
		.skilllim = {{5,10},{1,3}},
	},
	{.type = ET_JUDGE_CONSERVATIVE,
		.age = A_MIDDLEAGED,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_HRT,EA_INT,EA_WIS},
		.attrlim = {{1,1},{5,10},{10,10}},
		.gender = EG_MBIAS,
		.money = {20,60},
		.infiltration = {50,80},
		.juice = {100,150},
		.skill = {ES_LAW,ES_WRITING},
		.skilllim = {{5,10},{1,3}},
	},
	{.type = ET_AGENT,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{7,10},{5,10},{4,10},{5,10},{5,10}},
		.gender = EG_MBIAS,
		.infiltration = {0,150},
		.juice = {200,350},
		.skill = {ES_CLUB,ES_DODGE,ES_DRIVING,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE,ES_SHOTGUN,ES_SMG},
		.skilllim = {{2,9},{4,7},{4,9},{2,9},{2,9},{4,9},{2,9},{2,9},{2,9}},
	},
	{.type = ET_RADIOPERSONALITY,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_CHA,EA_WIS},
		.attrlim = {{10,10},{8,10}},
		.infiltration = {60,90},
		.juice = {100,150},
		.money = {50,100},
		.skill = {ES_PERSUASION},
		.skilllim = {{1,8}},
	},
	{.type = ET_NEWSANCHOR,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_CHA,EA_WIS},
		.attrlim = {{10,10},{8,10}},
		.infiltration = {60,90},
		.juice = {100,150},
		.money = {50,100},
	},
	{.type = ET_GENETIC,
		.age = A_DOGYEARS,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CHA,EA_HRT,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{1,20},{1,2},{1,6},{1,1},{1,20},{1,6}},
	},
	{.type = ET_GUARDDOG,
		.age = A_DOGYEARS,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_HRT,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{9,15},{1,6},{1,1},{7,12},{1,6}},
	},
	{.type = ET_PRISONER,
		.gender = EG_MBIAS,
		.juice = {-5,-5},
		.money = {0,1},
	},
	{.type = ET_JUROR,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.money = {0,1},
	},
	{.type = ET_LAWYER,
		.age = A_GRADUATE,
		.attrs = {EA_CHA,EA_INT},
		.attrlim = {{4,10},{6,10}},
		.money = {50,100},
		.skill = {ES_LAW,ES_PERSUASION},
		.skilllim = {{4,7},{2,5}},
	},
	{.type = ET_SEWERWORKER,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
	},
	{.type = ET_COLLEGESTUDENT,
		.age = {18,23},
		.money = {20,50},
		.skill = {ES_ART,ES_COMPUTERS,ES_MUSIC,ES_SCIENCE,ES_WRITING},
		.skilllim = {{0,2},{0,1},{0,2},{0,2},{1,2}},
	},
	{.type = ET_MUSICIAN,
		.age = A_MATURE,
		.money = {0,10},
		.skill = {ES_MUSIC,ES_SEDUCTION},
		.skilllim = {{2,5},{0,1}},
	},
	{.type = ET_MATHEMATICIAN,
		.age = A_MATURE,
		.attrs = {EA_INT},
		.attrlim = {{7,10}},
		.money = {20,50},
		.skill = {ES_COMPUTERS,ES_SCIENCE},
		.skilllim = {{0,2},{1,3}},
	},
	{.type = ET_TEACHER,
		.age = A_MATURE,
		.gender = EG_FBIAS,
		.money = {20,50},
		.skill = {ES_TEACHING},
		.skilllim = {{3,6}},
	},
	{.type = ET_HSDROPOUT,
		.age = A_TEENAGER,
		.money = {20,50},
	},
	{.type = ET_BUM,
		.age = A_YOUNGADULT,
		.money = {20,50},
		.align = ALIGN_ELITELIBERAL,
		.random_align = true, //will return anything but conservative.
	},
	{.type = ET_GANGMEMBER,
		.age = A_YOUNGADULT,
		.gender = EG_MBIAS,
		.juice = {-5,-5},
		.money = {20,50},
		.skill = {ES_PISTOL,ES_RIFLE,ES_SHOTGUN,ES_STREETSENSE},
		.skilllim = {{1,2},{1,2},{1,2},{2,3}},
	},
	{.type = ET_CRACKHEAD,
		.age = A_YOUNGADULT,
		.align = ALIGN_ELITELIBERAL,
		.random_align = true, //will return anything but conservative.
		.attrpts = {30,30},
		.attrs = {EA_INT},
		.attrlim = {{1,1}},
		.juice = {-20,-20},
		.money = {20,50},
	},
	{.type = ET_PRIEST,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_RELIGION},
		.skilllim = {{3,7}},
	},
	{.type = ET_ENGINEER,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_COMPUTERS,ES_SCIENCE},
		.skilllim = {{1,2},{1,3}},
	},
	{.type = ET_FASTFOODWORKER,
		.money = {20,50},
	},
	{.type = ET_BAKER,
		.money = {20,50},
	},
	{.type = ET_BARISTA,
		.age = A_YOUNGADULT,
		.money = {20,50},
	},
	{.type = ET_BARTENDER,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
	},
	{.type = ET_TELEMARKETER,
		.age = A_YOUNGADULT,
		.money = {20,50},
		.skill = {ES_PERSUASION},
		.skilllim = {{1,3}},
	},
	{.type = ET_CARSALESMAN,
		.age = A_MATURE,
		.money = {40,80},
		.skill = {ES_BUSINESS,ES_DRIVING,ES_PERSUASION},
		.skilllim = {{1,4},{1,3},{1,4}},
	},
	{.type = ET_OFFICEWORKER,
		.age = A_MATURE,
		.money = {20,50},
		.skill = {ES_BUSINESS},
		.skilllim = {{0,2}},
	},
	{.type = ET_FOOTBALLCOACH,
		.age = A_MIDDLEAGED,
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_PERSUASION,ES_TEACHING},
		.skilllim = {{2,5},{2,4}},
	},
	{.type = ET_PROSTITUTE,
		.age = A_YOUNGADULT,
		.align = ALIGN_LIBERAL,
		.random_align = true,
		.juice = {-5, -5},
		.money = {20, 50},
		.skill = {ES_PERSUASION,ES_SEDUCTION,ES_STREETSENSE},
		.skilllim = {{2,5},{2,5},{2,3}},
	},
	{.type = ET_MAILMAN,
		.age = A_MATURE,
		.money = {20,50},
	},
	{.type = ET_GARBAGEMAN,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_DRIVING},
		.skilllim = {{1,2}},
	},
	{.type = ET_PLUMBER,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
	},
	{.type = ET_CHEF,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
	},
	{.type = ET_CONSTRUCTIONWORKER,
		.age = A_MATURE,
		.attrs = {EA_CON,EA_STR},
		.attrlim = {{7,10},{7,10}},
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_DRIVING},
		.skilllim = {{1,2}},
	},
	{.type = ET_AMATEURMAGICIAN,
		.age = A_MATURE,
		.money = {20,50},
	},
	{.type = ET_TANK,
		.age = A_TEENAGER,
		.align = ALIGN_CONSERVATIVE,
		.gender = EG_NEUTRAL,
		.skill = {ES_HANDTOHAND},
		.skilllim = {{20,20}},
	},
	{.type = ET_MERC,
		.age = A_YOUNGADULT,
		.attrs = {EA_AGI,EA_CON,EA_STR,EA_WIS},
		.attrlim = {{5,10},{5,10},{5,10},{5,10}},
		.align = ALIGN_CONSERVATIVE,
		.gender = EG_MBIAS,
		.infiltration = {0,30},
		.juice = {0,100},
		.money = {0,1},
		.skill = {ES_DODGE,ES_DRIVING,ES_HANDTOHAND,ES_PSYCHOLOGY,ES_RIFLE,ES_SECURITY},
		.skilllim = {{0,4},{0,1},{0,2},{0,1},{2,5},{0,2}},
	},
	{.type = ET_HICK,
		.age= A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.gender = EG_MALE,
		.money = {6,11},
	},
	{.type = ET_SOLDIER,
		.age = A_YOUNGADULT,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_STR,EA_WIS},
		.attrlim = {{5,10},{5,10},{5,10},{5,10}},
		.gender = EG_MBIAS,
		.infiltration = {0,30},
		.juice = {0,100},
		.money = {0,1},
		.skill = {ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE},
		.skilllim = {{1,3},{1,3},{1,3},{1,3},{1,4}},
	},
	{.type = ET_VETERAN,
		.age = A_MIDDLEAGED,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{5,10},{5,10},{5,10}},
		.gender = EG_MBIAS,
		.infiltration={0,30},
		.juice = {0,100},
		.skill = {ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE},
		.skilllim = {{1,3},{1,3},{1,3},{1,3},{1,4}},
	},
	{.type = ET_HARDENED_VETERAN,
		.age = A_MIDDLEAGED,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{7,10},{7,10},{7,10}},
		.gender = EG_MBIAS,
		.infiltration={0,30},
		.juice = {0,100},
		.money = {0,1},
		.skill = {ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE,ES_SECURITY},
		.skilllim = {{2,4},{2,4},{2,4},{1,3},{4,7},{0,2}},
	},
	{.type = ET_PRISONGUARD,
		.age = A_MATURE,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{3,10},{3,10},{3,10}},
		.gender = EG_MBIAS,
		.infiltration={0,30},
		.skill = {ES_CLUB,ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_SHOTGUN},
		.skilllim = {{2,4},{0,1},{1,2},{1,2},{1,3}},
	},
	{.type = ET_HIPPIE,
		.age = {18,57},
		.align = ALIGN_LIBERAL,
		.attrpts = {35,35},
		.attrs = {EA_HRT,EA_WIS},
		.attrlim = {{6,15},{1,1}},
		.money = {20,50},
		.skill = {ES_ART,ES_MUSIC,ES_TAILORING},
		.skilllim = {{0,1},{0,1},{0,1}},
	},
	{.type = ET_CRITIC_ART,
		.age = A_MATURE,
		.money = {100,230},
		.skill = {ES_ART,ES_PERSUASION,ES_WRITING},
		.skilllim = {{1,4},{2,5},{2,5}},
	},
	{.type = ET_CRITIC_MUSIC,
		.age = A_MATURE,
		.money = {100,230},
		.skill = {ES_MUSIC,ES_PERSUASION,ES_WRITING},
		.skilllim = {{1,4},{2,5},{2,5}},
	},
	{.type = ET_SOCIALITE,
		.age = A_MATURE,
		.money = {100,230},
		.skill = {ES_ART,ES_MUSIC,ES_PERSUASION},
		.skilllim = {{0,2},{0,2},{1,3}},
	},
	{.type = ET_PROGRAMMER,
		.age = A_MATURE,
		.attrs = {EA_INT},
		.attrlim = {{3,10}},
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_COMPUTERS},
		.skilllim = {{4,8}},
	},
	{.type = ET_RETIREE,
		.age = A_SENIOR,
	},
	{.type = ET_PAINTER,
		.age = A_MATURE,
		.skill = {ES_ART},
		.skilllim = {{3,6}},
	},
	{.type = ET_SCULPTOR,
		.age = A_MATURE,
		.money = {100,230},
		.skill = {ES_PERSUASION, ES_WRITING},
		.skilllim = {{0,3},{4,7}},
	},
	{.type = ET_JOURNALIST,
		.age = A_MATURE,
		.juice = {0,25},
		.money = {100,230},
		.skill = {ES_PERSUASION,ES_WRITING},
		.skilllim = {{2,5},{2,5}},
	},
	{.type = ET_DANCER,
		.age = A_YOUNGADULT,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{10,10},{10,10},{4,10}},
		.skill = {ES_ART,ES_MUSIC},
		.skilllim = {{1,2},{1,2}},
	},
	{.type = ET_PHOTOGRAPHER,
		.age = A_MATURE,
		.skill = {ES_ART},
		.skilllim = {{2,3}},
	},
	{.type = ET_CAMERAMAN,
		.age = A_MATURE,
		.skill = {ES_ART},
		.skilllim = {{1,2}},
	},
	{.type = ET_HAIRSTYLIST,
		.age = A_MATURE,
		.gender = EG_FBIAS,
		.skill = {ES_ART},
		.skilllim = {{1,2}},
	},
	{.type = ET_FASHIONDESIGNER,
		.age = A_MATURE,
		.gender = EG_FBIAS,
		.skill = {ES_ART,ES_TAILORING},
		.skilllim = {{2,4},{3,10}},
	},
	{.type = ET_CLERK,
		.age = A_MATURE,
	},
	{.type = ET_THIEF,
		.age = A_MATURE,
		.skill = {ES_DISGUISE,ES_SECURITY,ES_STEALTH},
		.skilllim = {{3,7},{3,7},{3,7}},
	},
	{.type = ET_ACTOR,
		.age = A_MATURE,
		.attrs = {EA_CHA,EA_WIS},
		.attrlim = {{5,10},{9,10}},
		.skill = {ES_DISGUISE,ES_PERSUASION,ES_SEDUCTION},
		.skilllim = {{3,7},{0,4},{0,4}},
	},
	{.type = ET_YOGAINSTRUCTOR,
		.age = A_MATURE,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{10,10},{10,10},{4,10}},
		.gender = EG_FBIAS,
		.skill = {ES_TEACHING},
		.skilllim = {{2,5}},
	},
	{.type = ET_MARTIALARTIST,
		.age = A_MATURE,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{8,10},{6,10},{6,10}},
		.gender = EG_MBIAS,
		.skill = {ES_HANDTOHAND,ES_TEACHING},
		.skilllim = {{4,7},{1,3}},
	},
	{.type = ET_ATHLETE,
		.age = A_YOUNGADULT,
		.attrs = {EA_AGI,EA_CON,EA_STR},
		.attrlim = {{8,10},{8,10},{8,10}},
		.gender = EG_MBIAS,
	},
	{.type = ET_BIKER,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_DRIVING},
		.skilllim = {{3,5}},
	},
	{.type = ET_TRUCKER,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_DRIVING},
		.skilllim = {{3,5}},
	},
	{.type = ET_TAXIDRIVER,
		.age = A_MATURE,
		.gender = EG_MBIAS,
		.money = {20,50},
		.skill = {ES_DRIVING},
		.skilllim = {{3,5}},
	},
	{.type = ET_NUN,
		.age = A_MATURE,
		.gender = EG_FEMALE,
		.skill = {ES_RELIGION},
		.skilllim = {{5,7}},
	},
	{.type = ET_MUTANT,
		.age = A_MATURE,
		.align = ALIGN_LIBERAL,
		.attrpts = {7,66},
		.attrs = {EA_AGI,EA_CHA,EA_CON,EA_HRT,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{1,50},{1,50},{1,50},{1,50},{1,50},{1,50},{1,50}},
		.money = {20,50},
	},
	{.type = ET_DOCTOR,
		.age = A_GRADUATE,
		.attrs = {EA_INT},
		.attrlim = {{6,10}},
		.gender = EG_MBIAS,
		.skill = {ES_FIRSTAID},
		.skilllim = {{4,7}},
	},
	{.type = ET_NURSE,
		.age = A_GRADUATE,
		.gender = EG_FBIAS,
		.skill = {ES_FIRSTAID},
		.skilllim = {{1,4}},
	},
	{.type = ET_CCS_VIGILANTE,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrpts = {7,66},
		.attrs = {EA_AGI,EA_CHA,EA_CON,EA_HRT,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{4,20},{1,20},{4,20},{1,4},{1,20},{4,20},{8,20}},
		.gender = EG_MBIAS,
		.infiltration = {50,80},
		.juice = {90,210},
		.skill = {ES_BUSINESS,ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RELIGION,ES_RIFLE,ES_SHOTGUN},
		.skilllim = {{0,2},{2,5},{2,5},{3,6},{0,2},{1,3},{3,6},{3,6}},
	},
	{.type = ET_CCS_ARCHCONSERVATIVE,
		.age = A_MIDDLEAGED,
		.align = ALIGN_CONSERVATIVE,
		.attrpts = {7,66},
		.attrs = {EA_AGI,EA_CHA,EA_CON,EA_HRT,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{4,25},{1,25},{4,25},{1,1},{1,25},{4,25},{10,25}},
		.gender = EG_MBIAS,
		.infiltration = {90,100},
		.juice = {500,750},
		.money = {150,200},
		.skill = {ES_BUSINESS,ES_DODGE,ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RELIGION,ES_RIFLE,ES_SHOTGUN},
		.skilllim = {{0,5},{2,7},{4,7},{4,7},{6,9},{0,5},{2,7},{6,9},{6,9}},
	},
	{.type = ET_POLITICALACTIVIST,
	},
	{.type = ET_CCS_MOLOTOV,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrpts = {7,66},
		.attrs = {EA_AGI,EA_CHA,EA_CON,EA_HRT,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{6,20},{1,20},{6,20},{1,4},{1,20},{6,20},{8,20}},
		.gender = EG_MBIAS,
		.infiltration = {50,80},
		.juice = {90,210},
		.skill = {ES_BUSINESS,ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RELIGION,ES_THROWING},
		.skilllim = {{0,2},{2,5},{2,5},{0,2},{1,3},{2,5}},
	},
	{.type = ET_CCS_SNIPER,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrpts = {7,66},
		.attrs = {EA_AGI,EA_CHA,EA_CON,EA_HRT,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{6,20},{1,20},{6,20},{1,4},{1,20},{6,20},{8,20}},
		.gender = EG_MBIAS,
		.infiltration = {50,80},
		.juice = {90,210},
		.skill = {ES_BUSINESS,ES_DRIVING,ES_HANDTOHAND,ES_PISTOL,ES_PSYCHOLOGY,ES_RELIGION,ES_RIFLE},
		.skilllim = {{0,2},{2,5},{2,5},{0,2},{1,3},{6,9}},
	},
	{.type = ET_PSYCHOLOGIST,
		.age = A_GRADUATE,
		.attrs = {EA_HRT,EA_INT},
		.attrlim = {{6,10},{6,10}},
		.gender = EG_MBIAS,
		.skill = {ES_PSYCHOLOGY},
		.skilllim = {{4,7}},
	},
	{.type = ET_LOCKSMITH,
		.age = A_MATURE,
		.skill = {ES_SECURITY},
		.skilllim = {{3,7}},
	},
	{.type = ET_MILITARYPOLICE,
		.age = A_YOUNGADULT,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_STR,EA_WIS},
		.attrlim = {{7,10},{7,10},{7,10},{7,10}},
		.gender = EG_MBIAS,
		.infiltration = {10,40},
		.juice = {100,150},
		.money = {0,1},
		.skill = {ES_DODGE,ES_HANDTOHAND,ES_PSYCHOLOGY,ES_RIFLE},
		.skilllim = {{2,5},{3,5},{3,5},{4,7}},
	},
	{.type = ET_MILITARYOFFICER,
		.age = A_MIDDLEAGED,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_CHA,EA_INT,EA_WIS},
		.attrlim = {{7,10},{7,10},{10,10}},
		.gender = EG_MBIAS,
		.infiltration = {50,80},
		.juice = {100,150},
		.money = {0,1},
		.skill = {ES_HANDTOHAND,ES_PERSUASION,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE},
		.skilllim = {{1,6},{3,7},{1,6},{1,6},{1,2}},
	},
	{.type = ET_BANK_TELLER,
		.age = A_MATURE,
		.align = ALIGN_MODERATE,
	},
	{.type = ET_BANK_MANAGER,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_INT,EA_WIS},
		.attrlim = {{4,10},{4,10}},
		.money = {120,240},
		.skill = {ES_BUSINESS},
		.skilllim = {{3,6}},
	},
	{.type = ET_SECRET_SERVICE,
		.age = A_MATURE,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_AGI,EA_CON,EA_INT,EA_STR,EA_WIS},
		.attrlim = {{7,10},{5,10},{4,10},{5,10},{5,10}},
		.gender = EG_MBIAS,
		.infiltration = {0,150},
		.juice = {200,300},
		.skill = {ES_DODGE,ES_DRIVING,ES_PISTOL,ES_PSYCHOLOGY,ES_RIFLE,ES_SMG},
		.skilllim = {{4,9},{4,9},{4,9},{4,9},{4,9},{4,9}},
	},
	{.type = ET_POLITICIAN, .gender = EG_MBIAS,
		.age = A_MIDDLEAGED,
		.align = ALIGN_CONSERVATIVE,
		.attrs = {EA_WIS},
		.attrlim = {{6,10}},
		.infiltration = {80,95},
		.juice = {400,800},
		.money = {40,80},
		.skill = {ES_LAW,ES_PERSUASION},
		.skilllim = {{1,7},{5,8}},
	},
};
